title: "selfdrivenAI"
description: "Combining the selfdriven Framework with the power of Generative AI to enable decentralised human/purpose driven communities"
baseurl: ""
url: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
